### ISSUE TITLE
AttributeError: 'function' object has no attribute 'size'

### ISSUE THREAD

**Issue by jinganglang567** [zhanglijun95/ZoDiac#2]
File "/mnt/sda/tgf/qingjiaotgf/demo.py", line 100, in <module>
    loss = totalLoss(pred_img_tensor, gt_img_tensor, init_latents_wm, wm_pipe)
  File "/mnt/sda/tgf/qingjiaotgf/loss/loss.py", line 27, in __call__
   
AttributeError: 'function' object has no attribute 'size'
 self.loss_img, self.loss_w = nn.MSELoss(), nn.L1Loss()
lossI = self.loss_img(pred_img_tensor, gt_img_tensor)*self.loss_weights[0]

sorry to bother you doctor,i got this problem,Can you tell me how to solve it

**Comment by zhanglijun95** [comment]
Hi, it seems that you didn't paste the full error message. Could you figure out where you use the '.size'?

**Comment by jinganglang567** [comment]
File "/mnt/sda/tgf/qingjiaotgf/demo.py", line 100, in <module>
    loss = totalLoss(pred_img_tensor, gt_img_tensor, init_latents_wm, wm_pipe)
  File "/mnt/sda/tgf/qingjiaotgf/loss/loss.py", line 29, in __call__
    lossI = self.loss_img(pred_img_tensor, gt_img_tensor)*self.loss_weights[0]
  File "/opt/anaconda3/envs/tgf_qingjiao/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/anaconda3/envs/tgf_qingjiao/lib/python3.10/site-packages/torch/nn/modules/loss.py", line 536, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/opt/anaconda3/envs/tgf_qingjiao/lib/python3.10/site-packages/torch/nn/functional.py", line 3281, in mse_loss
    if not (target.size() == input.size()):
AttributeError: 'function' object has no attribute 'size'

**Comment by jinganglang567** [comment]
sorry to bother you again,doctor i found the type of pred_img_tensor is <class 'function'>

**Comment by zhanglijun95** [comment]
According to the code in Example.ipynb, the pred_img_tensor is generated by the stable diffusion pipeline as `pred_img_tensor = pipe('', guidance_scale=1.0, num_inference_steps=50, output_type='tensor', use_trainable_latents=True, init_latents=init_latents_wm).images`. You may want to check how to call the pipeline to generate the image tensor and whether the pipeline you are using is generating the predicted image.

**Comment by jinganglang567** [comment]
thanks for your reply doctor,i have another question about the     
def decode_latents_tensor(self, latents):
        latents = 1 / self.vae.config.scaling_factor * latents
        image = self.vae.decode(latents).sample
        image = (image / 2 + 0.5).clamp(0, 1)
        # we always cast to float32 as this does not cause significant overhead and is compatible with bfloat16
        # image = image.cpu().permute(0, 2, 3, 1).float().numpy()
        return image
the function is in the class named WatermarkStableDiffusionPipeline in wmdiffusion
does it need @torch.inference_model()?

**Comment by zhanglijun95** [comment]
No it must be in the train mode since we need the gradient during watermarking.

**Comment by jinganglang567** [comment]
ok,thank you doctor but it always torch out of memeory when i watermark the image,my gpu is 1080ti which has 11G memory.how to solve it?

**Comment by jinganglang567** [comment]
Can this use multiple gpus?

**Comment by zhanglijun95** [comment]
Stable diffusion 2.1 base is right larger than 11G. I remember it's about 15000MB. You can try other stable diffusion baseline or write muti-gpu version.

**Comment by jinganglang567** [comment]
yes, actually i want to know does it have any technology for muti-gpu for sd baseline?

**Comment by zhanglijun95** [comment]
No. It's just a PyTorch model, so any multi-gpu tool can be used for it.

**Comment by jinganglang567** [comment]
sorry doctor,you mean this https://huggingface.co/docs/accelerate/usage_guides/distributed_inference  ,i try it before,but it doesn't work for this

**Comment by zhanglijun95** [comment]
That's for inference. We're not just doing inference here. Please try to set smaller number of inference steps in diffusion pipeline.

**Comment by jinganglang567** [comment]
![image](https://github.com/user-attachments/assets/80bd303e-935e-42af-8250-955d863cdda9)
yes i set this but it didn't work

**Comment by jinganglang567** [comment]
sorry to bother you,doctor,if we want to use the muti-gpu ,how we need to change the code？

**Comment by zhanglijun95** [comment]
> ![image](https://private-user-images.githubusercontent.com/71933496/348521165-80bd303e-935e-42af-8250-955d863cdda9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NjYyOTcsIm5iZiI6MTcyMDk2NTk5NywicGF0aCI6Ii83MTkzMzQ5Ni8zNDg1MjExNjUtODBiZDMwM2UtOTM1ZS00MmFmLTgyNTAtOTU1ZDg2M2NkZGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDE0MDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhYjNjNTY3NzU2NTZlYTA2YzllYmEyYzYzNTUwMmJjOWZkZWI1OWNjYTI0OGVmZDEzYTNhMmExZDkwMjAwMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SnA18KSkg8sREPs2ZHhtc2CD_rV367qLBGoarlINCz8) yes i set this but it didn't work

I don't know where you set it, but if you are using Example.ipynb, it is set as 50 directly and needs to be modify. 
I believe most of multi-gpu will need some coding, but I don't think you have to use it. Correctly setting up the step will solve the problem.

**Comment by jinganglang567** [comment]
thanks for your reply,doctor i will try again
